### ISSUE TITLE
The type initializer for 'LgLcd.Applet' threw an exception.

### ISSUE THREAD

**Issue by XceSx6** [zzattack/Logitech-LCD#2]
Wanna do a trial run, and convert my G15 software to work for G19 with this.
Your code is very cleanly written, but i can't get the test form to run..
Stopped on a TypeInitializationException: An unhandled exception of type 'System.TypeInitializationException' occurred in LgLcd.NET.dll
Located in: WinFormsApples.cs: protected void InitializeApplet() {: _applet = new AppletProxy(this);
Exception: The type initializer for 'LgLcd.Applet' threw an exception.

Any help getting this working so i can try some stuff out would be awesome

**Comment by zzattack** [comment]
Probably the lglcd.dll file missing somewhere. Simplest is usually to target for x86 instead of AnyCPU.

**Comment by XceSx6** [comment]
Omg, that was it! Just had to copy the lglcd.dll to the debug folder! Thanks zzattack :)
